#!/usr/bin/perl

use strict;
use File::Temp qw(tempfile);
use File::Path;

$ENV{PATH} = "/local/mysql/server/bin:" . $ENV{PATH};
my @ts = localtime(time);

my $tstamp = sprintf( "%.4d%.2d%.2d-%.2d%.2d", $ts[5] + 1900, $ts[4] + 1, $ts[3], $ts[2], $ts[1] );

my $base = "/local/mysql-db-backups";

system("/local/mysql/clean-backups");

system( "mkdir", "-p", "$base/latest" );

# DO NOT EVER USE --skip-opt, it throws away important
# stuff like auto_increment flags

my $datadir = "/local/mysql/data";

# Generate a merged config file from several other files

umask(077);
my ( $fh, $tmpfile ) = tempfile();

my @configs = ( "/etc/my.cnf", "/local/mysql/mysql-base.conf", "/local/mysql/mysql.conf", "/root/.my.cnf" );
foreach my $cfile (@configs) {
    next if ( !-e $cfile );
    open( my $in, "<$cfile" );
    while ( defined( my $line = <$in> ) ) {
        print $fh $line;
    }
    close($in);
    print $fh "\n\n";
}
close($fh);

my $db = "all-master";

my $md_cmd = "mysqldump";
if ( -e "/local/mysql/server/bin/mariadb-dump" ) {
    $md_cmd = "mariadb-dump";
}

my $gzip = "gzip -v";
if ( -e "/usr/bin/pigz" ) {
    $gzip = "/usr/bin/pigz";
}

my $cmd
    = "${md_cmd} --defaults-file=$tmpfile --flush-logs --master-data --all-databases --single-transaction | $gzip --rsyncable -1 -c - > $base/latest/${db}.gz";
print "+ $cmd\n";
system($cmd);

my $dest = sprintf( "%s/data/%s/%.4d/%.2d/%.2d", $base, $db, $ts[5] + 1900, $ts[4] + 1, $ts[3] );

system( "mkdir", "-p", "$dest" );

my @cmd = ( "cp", "$base/latest/${db}.gz", "$dest/${tstamp}.gz" );
print "+ ", join( " ", @cmd ), "\n";
system(@cmd);

unlink($tmpfile);

print "Cleaning backups dir...\n";
system("/local/mysql/clean-backups");
