#!/bin/sh -x

cd /local/mysql

/local/mysql/setup-local-dirs $*

# Handle deprecated variable names
perl -pi -e "s/table_cache=/table_open_cache=/go" /local/mysql/mysql.conf
perl -pi -e "s/key_buffer=/key_buffer_size=/go" /local/mysql/mysql.conf
perl -pi -e "s/sort_buffer=/sort_buffer_size=/go" /local/mysql/mysql.conf
perl -pi -e "s/join_buffer=/join_buffer_size=/go" /local/mysql/mysql.conf
perl -pi -e "s/myisam-recover=/myisam-recover-options=/go" /local/mysql/mysql.conf
perl -pi -e "s/#*(innodb_additional_mem_pool_size)/#\1/go" /local/mysql/mysql.conf
perl -pi -e "s/#*(innodb_locks_unsafe_for_binlog)/#\1/go" /local/mysql/mysql.conf
perl -pi -e "s/#*(innodb_file_format)/#\1/go" /local/mysql/mysql.conf

# No longer needed
perl -pi -e "s/#*(wsrep_debug)/#\1/go" /local/mysql/mysql.conf

/local/mysql/rc.mysqld

sleep 10

if [ -e "/local/mysql/cluster" ]; then
	sleep 10
fi

/local/mysql/sbin/wrap-exec-root mariadb-upgrade
