#!/usr/bin/perl

use strict;
use File::Temp qw(tempfile);
use File::Path;
use Getopt::Long;
use JSON;

my $config = {};
open( my $in, "/local/mysql/backups.conf" );
my $raw = join( "", <$in> );
close($in);
eval { $config = decode_json($raw); };

my $help;
my $debug;
my $skip_lock_tables;
my $single_transaction;
my $database;

if ( $config->{settings}->{"single-transaction"} ) {
    $single_transaction = 1;
}
if ( $config->{settings}->{"skip-lock-tables"} ) {
    $skip_lock_tables = 1;
}

my $res = GetOptions(
    "skip-lock-tables+"   => \$skip_lock_tables,
    "single-transaction+" => \$single_transaction,
    "help+"               => \$help,
    "debug+"              => \$debug,
    "database|db=s"       => \$database
);

if ( !$res || $help ) {
    print "$0 [--skip-lock-tables] [--single-transaction] [--help] [--debug] [--database db]\n";
    exit(0);
}

$ENV{PATH} = "/local/mysql/server/bin:" . $ENV{PATH};
my @ts = localtime(time);

my $tstamp = sprintf( "%.4d%.2d%.2d-%.2d%.2d", $ts[5] + 1900, $ts[4] + 1, $ts[3], $ts[2], $ts[1] );

my $base = "/local/mysql-db-backups";

system("/local/mysql/clean-backups");

system( "mkdir", "-p", "$base/latest" );

# DO NOT EVER USE --skip-opt, it throws away important
# stuff like auto_increment flags

my $datadir = "/local/mysql/data";

# Generate a merged config file from several other files

umask(077);
if ( !-d "/local/mysql/tmp" ) {
    mkdir("/local/mysql/tmp");
    system( "chown", "mysql:mysql", "/local/mysql/tmp" );
}
my ( $fh, $tmpfile ) = tempfile( "mysql-backups-XXXXXX", DIR => "/local/mysql/tmp", SUFFIX => ".conf" );

my @configs = ( "/etc/my.cnf", "/local/mysql/mysql-base.conf", "/local/mysql/mysql.conf", "/root/.my.cnf" );
foreach my $cfile (@configs) {
    next if ( !-e $cfile );
    open( my $in, "<$cfile" );
    while ( defined( my $line = <$in> ) ) {
        print $fh $line;
    }
    close($in);
    print $fh "\n\n";
}
close($fh);

opendir( my $dbdir, $datadir );
while ( my $db = readdir($dbdir) ) {
    next if ( $db eq "." || $db eq ".." );
    next if ( $db eq "lost+found" );
    next if ( $db eq "performance_schema" );
    next if ( $database && $db ne $database );
    next if ( !-d "$datadir/$db" );
    next if ( !-e "$datadir/$db/db.opt" && !glob("$datadir/$db/*.frm") );

    # Unsafe, but cuts impact
    my $locks = "";
    if ($skip_lock_tables) {
        $locks = "--skip-lock-tables";
    }

    my $single = "";
    if ($single_transaction) {
        $single = "--single-transaction";
    }

    my $md_cmd = "/local/mysql/sbin/wrap-exec mariadb-dump";

    my $gzip = "gzip -v";
    if ( -e "/usr/bin/pigz" ) {
        $gzip = "/usr/bin/pigz";
    }

    my $cmd
        = "${md_cmd} --defaults-file=$tmpfile $locks $single $db | $gzip --rsyncable -1 -c - > $base/latest/${db}.gz";
    print "+ $cmd\n";
    system($cmd);

    my $dest = sprintf( "%s/data/%s/%.4d/%.2d/%.2d", $base, $db, $ts[5] + 1900, $ts[4] + 1, $ts[3] );

    system( "mkdir", "-p", "$dest" );

    my @cmd = ( "cp", "$base/latest/${db}.gz", "$dest/${tstamp}.gz" );
    print "+ ", join( " ", @cmd ), "\n";
    system(@cmd);
}

unlink($tmpfile);

print "Cleaning backups dir...\n";
system("/local/mysql/clean-backups");

if ( !-e "/local/mysql-db-backups/skip-analyze" ) {
    print "Auto checking tables...\n";
    if ($database) {
        system( "/local/mysql/sbin/wrap-exec", "mariadb-check", "-a", $database );
    }
    else {
        system( "/local/mysql/sbin/wrap-exec", "mariadb-check", "-A", "-a" );
    }
}
