#!/usr/bin/perl

use strict;
use Getopt::Long;

my $help    = 0;
my $cluster = 0;

my $tag;
if ( -e "/local/mysql/tag.txt" ) {
	open(my $in, "/local/mysql/tag.txt");
	chomp($tag = <$in>);
	close($in);
}
else {
	open(my $in, "/local/mysql/defaults/tag.txt");
	chomp($tag = <$in>);
	close($in);
}

my $skip  = 0;
my $debug = 0;
my $force = 0;
my $seed;
if ( -e "/local/mysql/cluster" ) {
    $cluster = 1;
}

my @save_argv = @ARGV;
print "$0: launched with ", join( " ", @ARGV ), "\n";

my $res = GetOptions(
    "debug+"       => \$debug,
    "cluster"      => \$cluster,
    "force"        => \$force,
    "help"         => \$help,
    "tag=s"    => \$tag,
    "skip"         => \$skip
);
if ( !$res || $help ) {
    print
        "Usage: $0 [--tag=$tag] [--cluster] [--skip] [--debug] [--help]\n";
    exit(1);
}

if ( !-e "/local/mysql" ) {
    print "Must run from /local/mysql.\n";
    die;
}

if ( !getpwnam("mysql") ) {
    print "Userid 'mysql' must exist:\n\n";
    print "  Fedora/RH/CentOS: adduser -d /local/mysql mysql\n";
    print "  Ubuntu: adduser --quiet --gecos \"\" --disabled-password --home /local/mysql mysql\n";
    die;
}

# Rewrite tag file, including if it doesn't exist
open(my $out, ">/local/mysql/tag.txt");
print $out $tag, "\n";
close($out);

# Determine compiled in paths for system libs
my $def_socket = "/var/lib/mysql/mysql.sock";
if ( -e "/usr/bin/mysql" ) {
    open( my $in, "-|", "strings", "/usr/bin/mysql" );
    while ( defined( my $line = <$in> ) ) {
        if ( $line =~ m|^(/.*mysqld*.sock)$|o ) {
            $def_socket = $1;
            print "Found default socket from /usr/bin/mysql: $def_socket\n";
        }
    }
    close($in);
}

if ( -e "/usr/bin/apt-get" ) {
    $ENV{DEBIAN_FRONTEND} = "noninteractive";
    $is_deb = 1;
}

chdir("/local/mysql") || die;

print "Attempting update of /local/mysql installation with tag $tag.\n";
if ($cluster) {
    print "Cluster mode is enabled.\n";
}
print "\n";

if ( $cluster && !-e "/local/mysql/cluster" ) {
    open( my $out, ">/local/mysql/cluster" );
    print $out "\n";
    close($out);
}

if ( !$skip ) {
    print "Attempting update from repository...\n";
    if ( -e "/local/mysql/.git" ) {
        system("git config --global --add safe.directory /local/mysql");
        system("git pull");
    }
    print "Done.\n";

    # re-exec to get latest changes
    print "Re-executing self to get latest changes...\n";
    my @cmd = ( $0, "--skip", @save_argv );
    print "Command: ", join( " ", @cmd ), "\n";
    exec(@cmd);
    die "failed to re-exec self.\n";
}

system( "mkdir", "-p", "/local/mysql/data" );
system( "mkdir", "-p", "/var/lib/mysql" );
system( "chown", "-R", "mysql:mysql", "/var/lib/mysql" );

if ( !-e "/local/mysql/mysql.conf" ) {
    print "Installing base config...\n";
    system( "cp", "/local/mysql/defaults/mysql.conf", "/local/mysql/mysql.conf" );
}

if ( -d "/etc/mysql" ) {
    unlink("/etc/mysql/my.cnf");
    system( "cp",    "/local/mysql/defaults/client.conf", "/etc/mysql/my.cnf" );
    system( "chown", "root:root",                "/etc/mysql/my.cnf" );
}

unlink("/etc/my.cnf");
system( "cp",    "/local/mysql/defaults/client.conf", "/etc/my.cnf" );
system( "chown", "root:root",                "/etc/my.cnf" );

unlink( glob("/home/local/adm/rc-start/rc.*.mysql") );
symlink( "/local/mysql/rc.mysqld", "/home/local/adm/rc-start/rc.400.mysql" );

system( "rm",    "-rf", "/local/mysql-db-backups/bin" );
system( "mkdir", "-p",  "/local/mysql-db-backups/data" );
system( "mkdir", "-p",  "/local/mysql-db-backups/latest" );
system( "chown", "-R",  "mysql:mysql", "/local/mysql" );

#
# Modify socket path in various config files
#
foreach my $cfile ( "/etc/mysql/my.cnf", "/etc/my.cnf", "/local/mysql/mysql.conf" ) {
    next if ( !-e $cfile );
    print "Updating socket path in $cfile.\n";

    open( my $in, "<$cfile" );
    my $cfg = join( "", <$in> );
    close($in);

    my $newcfg = $cfg;
    $newcfg =~ s/^socket=.*?$/socket=$def_socket/sgm;

    if ( $newcfg ne $cfg ) {
        print "Writing new version of changed file ($cfile).\n";
        open( my $out, ">$cfile" );
        print $out $newcfg;
        close($out);
    }
}

# Make sure we have mysql client installed
if ( !-e "/usr/bin/mysql" ) {
	if ( $os =~ /bookworm/ ) {
		system( "apt-get", "-y", "install", "mariadb-client" );
	}
	else {
		system( "apt-get", "-y", "install", "mysql-client" );
	}
}

print "MySQL local directory setup completed.\n";
