#!/bin/bash

if [ -e /local/mysql/tag.txt ]; then
  TAG=$(cat /local/mysql/tag.txt)
else
  TAG=$(cat /local/mysql/defaults/tag.txt)
fi

ARGS=""
ARGS="-v /local/mysql:/local/mysql"
if [ ! -e /var/run/mysqld ]; then
  mkdir /var/run/mysqld
  chown mysql:mysql /var/run/mysqld
fi
ARGS="$ARGS -v /var/run/mysqld:/var/run/mysqld"

if [ -e /root/.my.cnf ]; then
  ARGS="$ARGS -v /root/.my.cnf:/root/.my.cnf"
fi

mkdir -p /local/mysql/data
chown mysql:mysql /local/mysql/data
ARGS="$ARGS -v /local/mysql/data:/var/mysql/data"

mkdir -p /var/run/mysql
chown mysql:mysql /var/run/mysql
ARGS="$ARGS -v /var/run/mysql:/var/run/mysql"

docker run \
  --rm -it \
  --network host \
  --user 0:0 \
  --ulimit nofile=16000:16000 \
  $ARGS \
  mariadb:$TAG \
  "$@"

