#!/bin/bash

if [ -e /local/mysql/tag.txt ]; then
  TAG=$(cat /local/mysql/tag.txt)
else
  TAG=$(cat /local/mysql/defaults/tag.txt)
fi

ARGS=""
ARGS="-v /local/mysql:/local/mysql"

mkdir -p /var/run/mysqld
chown mysql:mysql /var/run/mysqld
ARGS="$ARGS -v /var/run/mysqld:/var/run/mysqld"

mkdir -p /local/mysql/data
chown mysql:mysql /local/mysql/data
ARGS="$ARGS -v /local/mysql/data:/var/mysql/data"

mkdir -p /var/run/mysql
chown mysql:mysql /var/run/mysql
ARGS="$ARGS -v /var/run/mysql:/var/run/mysql"

docker run \
  --rm -it \
  --network host \
  --user $(id -u mysql):$(id -g mysql) \
  --ulimit nofile=16000:16000 \
  $ARGS \
  mariadb:$TAG \
  "$@"

