#!/bin/bash

if [ -e /local/mysql/tag.txt ]; then
  TAG=$(cat /local/mysql/tag.txt)
else
  TAG=$(cat /local/mysql/defaults/tag.txt)
fi

ARGS=""
ARGS="-v /local/mysql:/local/mysql"
if [ -e /var/run/mysqld ]; then
  ARGS="$ARGS -v /var/run/mysqld:/var/run/mysqld"
fi

mkdir -p /local/mysql/data
chown mysql:mysql /local/mysql/data
ARGS="$ARGS -v /local/mysql/data:/var/mysql/data"

docker run \
  --rm -it \
  --network host \
  --user $(id -u mysql):$(id -g mysql) \
  $ARGS \
  mariadb:$TAG \
  "$@"

